### ISSUE TITLE
謝謝你完成作業

### ISSUE THREAD

**Issue by azole** [Cindy55529/git-workshop#1]
謝謝你完成作業，筆記整得很好，資訊整理是很重要的能力，因為工程師要學的東西實在太多了，需要自己有能力去整理、吸收，甚至是收藏這些資訊，未來繼續保持！

**Comment by Cindy55529** [comment]
謝謝老師回覆，給予我莫大的鼓勵，以後會更認真交作業的！

azole ***@***.***>於 2021年7月29日 週四，下午11:20寫道：
